<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0;net11.0</TargetFrameworks>
    <LangVersion>preview<!--      LATEST      --></LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DebugType>embedded</DebugType>

    
    
    
    <!--      REMOVE      -->
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    
    
    
    
  </PropertyGroup>

  <Import Project="../NuGet.Build.props" />

  <ItemGroup Condition=" '$(TargetFramework)' != 'netstandard2.0' ">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="" />
    <None Include="../G4mvc.png" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
