<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net11.0</TargetFrameworks>
    <LangVersion>preview<!--      LATEST      --></LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    
    <!--      REMOVE      -->
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    
    
    
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.9.0" />
    <PackageReference Include="MSTest" Version="4.4.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing" Version="1.1.4" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    <PackageReference Include="System.Linq.AsyncEnumerable" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="System.Text.Json" Version="11.0.0-rc.1.26425.128" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\G4mvc.Generator\G4mvc.Generator.csproj" />
    <ProjectReference Include="..\..\G4mvc\G4mvc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Areas\**\*.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
    <None Update="Areas\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Compile Update="Controllers\**\*.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
    <Compile Update="Pages\**\*.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
    <None Update="Controllers\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Compile Update="Models\**\*.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
    <None Update="Models\**\*.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Pages\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Views\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="wwwroot\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="wwwrootAlt\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
