name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-dotnet@v4
      with:
       dotnet-version: '9.x.x'

    - uses: actions/checkout@v3
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v4
      with:
       dotnet-version: '8.x.x'
    - uses: actions/setup-dotnet@v4
      with:
       dotnet-version: '9.x.x'

    - uses: actions/checkout@v3
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
