name: Release

on:
  workflow_dispatch:
  
env:
  Major: 3
  Minor: 0
  Patch: 0

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Release Version
      run: |
        echo "VERSION=$Major.$Minor.$Patch" >> $GITHUB_ENV
      if: ${{ github.ref_name == 'main' }}

    - name: Prerelease Version
      run: |
        echo "VERSION=$Major.$Minor.$Patch-preview.$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      if: ${{ github.ref_name != 'main' }}

    - name: Version
      run: |
        echo $env.Version

    - name: Pack Release
      run:  dotnet pack -p:VersionPrefix=${{ env.Major }}.${{ env.Minor }}.${{ env.Patch }}
      if: ${{ github.ref_name == 'main' }}
    
    - name: Pack Prerelease
      run:  dotnet pack -p:VersionPrefix=${{ env.Major }}.${{ env.Minor }}.${{ env.Patch }};VersionSuffix=preview.${{ vars.GITHUB_RUN_NUMBER }}
      if: ${{ github.ref_name != 'main' }}
